---
- name: Update apt cache.
  apt:
    update_cache: yes
    cache_valid_time: 3600
- name: Install prerequesits for squeezeplay-pulse
  apt:
    pkg: libpulse0
- name: Check if squeezeplay version already installed
  stat:
    path: /opt/squeezeplay-{{ squeezeplay_version }}
  register: squeezeplay_directory
  tags: squeezeplay
- name: Download squeezeplay {{ squeezeplay_version }}
  get_url:
    url: "https://sourceforge.net/projects/lmsclients/files/squeezeplay/linux/squeezeplay-pulse-{{ squeezeplay_version }}-x86_64.tgz"
    checksum: "sha1:{{ squeezeplay_sha1 }}"
    dest: "/tmp/squeezeplay-{{ squeezeplay_version }}.zip"
    mode: 0644
  tags: squeezeplay
  when: not squeezeplay_directory.stat.exists
- name: Create squeezeplay directory
  file:
    path: "/opt/squeezeplay-{{ squeezeplay_version }}"
    state: directory
    mode: 0775
  tags: squeezeplay
- name: Install squeezeplay
  unarchive:
    src: "/tmp/squeezeplay-{{ squeezeplay_version }}.zip"
    dest: "/opt/squeezeplay-{{ squeezeplay_version }}"
    mode: 0644
    remote_src: yes
  tags: squeezeplay
  when: not squeezeplay_directory.stat.exists
- name: Symlink default squeezeplay to {{ squeezeplay_version }}
  file:
    src: "squeezeplay-{{ squeezeplay_version }}"
    dest: "/opt/squeezeplay"
    state: link
  tags: squeezeplay
- name: Symlink squeezeplay bin
  file:
    src: "/opt/squeezeplay/bin/squeezeplay.sh"
    dest: "/usr/local/bin/squeezeplay"
    state: link
  tags: squeezeplay
- name: Create launcher directory
  file:
    path: /usr/local/share/applications
    state: directory
    mode: 0755
- name: Copy Squeezeplay desktop launcher
  copy:
    src: squeezeplay.desktop
    dest: /usr/local/share/applications/squeezeplay.desktop
    mode: 0644
